### ISSUE TITLE
Uncaught (in promise) SyntaxError: The requested module '/node_modules/pdfjs-dist/build/pdf.js?v=a9f48987' does not provide an export named 'GlobalWorkerOptions'

### ISSUE THREAD

**Issue by dciug** [gspasov/svelte-pdf-simple#1] opened 2022-05-10 16:03 UTC
I'm just trying out the example in the Readme.

**Comment by gspasov** [comment] 2022-05-16 06:02
I created a brand new svelte project, installed the library and setup one of the examples. Everything seems to be working fine on my end, so I'm curious what is different for you in order to fail.

Could you provide me a little bit more details?
- Are you using `svelte` or `svelte-kit`;
- Are you using js/ts for your project;
- What version of Node are you using;
- Could you show me the example that does not work for you;

You could just as well give me a repo with the issue reproduced. And I could look into that as well.

PS. Although I saw that my first few examples don't have a closing tag.. Will be fixing that.

**Comment by dciug** [comment] 2022-05-24 12:18
npm: v8.5.5
node: v17.9.0
svelte: v3.48.0
Running on svelte-kit@next with TypeScript. For now, i'm using the built-in browser PDF viewer, but i'll come back to this project to try it again.

**Comment by gspasov** [comment] 2022-05-25 06:31
Thank you for the info, I'll try to reproduce the issue.

**Comment by gspasov** [comment] 2022-05-25 16:40
I created a new `svelte-kit` project using `npm init svelte@next` and setup a Skeleton project with TypeScript. Set my `node` version to `v17.9.0`. My `svelte` and `npm` are the same version as yours.

I went to `index.svelte` and added the following code:
```svelte
<script lang="ts">
  import { PdfViewer } from "svelte-pdf-simple";
  const pathToPdf = "./acord.pdf";
</script>

<PdfViewer url={pathToPdf} />
```
Inside the `/static` folder I added my `acord.pdf` PDF and the pdf is loaded normally with no errors in the terminal or browser console.

_(I tested all my other examples as well and they work just fine)_


I'm assuming that you are doing something different. If you could create a repository with the issue reproduced I'll be happy to look into it. Or guide me into what are you doing differently in order for me to catch the issue.

**Comment by xellDart** [comment] 2022-08-15 04:51
Same error:

Node: 16.16.6
Sveltekit all dependencies to next in package.json
Using node-adapter

**Comment by gspasov** [comment] 2022-08-18 13:00
Are you getting this error with the example in the README or with something else?

**Comment by gspasov** [comment] 2022-10-08 20:37
I'm going to close this issue since I'm unable to reproduce it. If someone could provide a repo with reproduction where I could look into it feel free to re-open the issue.

**Closed as completed by gspasov** 2022-10-08 20:37 UTC
